### PR TITLE
Making a stupid change

### PR DESCRIPTION
**Pull request by mmundt**
## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED by label AT: PRE-TEST INSPECTED! Autotester is Removing Label; this inspection will remain valid until a new commit to source branch is performed.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 3</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_BRANCH</td>
    <td>autotester</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/mmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>59845504eac87103719ff18e22122ac5b0d49625</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>c2e92b97a8b12705dcd6962310895fcd893a26e8</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (mmundt/pyomo)</dt>
  <ul>
    <li>Branch: autotester</li>
    <li>SHA: 59845504eac87103719ff18e22122ac5b0d49625</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: mmundt
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - ERROR: A user has commited a change to the PR before testing completed.  The testing SHA = 59845504eac87103719ff18e22122ac5b0d49625 Does not match the current commit SHA = 86b2fa601d49ad3ee96e9138f7f84ffeda05573a.  Testing of this PR must occur again.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           ERROR: LABEL SET BY UNAPPROVED USER, INSPECTION IS INVALID! - This PR must be re-inspected by whitelisted user.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 4</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_BRANCH</td>
    <td>autotester</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/mmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>b256659937be36f112b9eb695169e0c6f26daa14</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>fec3bc5ebf862e3afb1ee4afa7d0fe40a6d3f7d9</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (mmundt/pyomo)</dt>
  <ul>
    <li>Branch: autotester</li>
    <li>SHA: b256659937be36f112b9eb695169e0c6f26daa14</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: mmundt
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

**Review by rmmilewi — APPROVED** [review]
The performance of this new method is significantly better than the baseline on a number of problems of interest, and we have several customers requesting that we push this feature forward. Given that the tests are passing and the documentation is in order, I'm fine with approving this PR.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ rmmilewi ]!

**Comment by mrmundt** [comment]
NOTICE: The AutoTester has encountered an internal error (usually a Communications Timeout), testing will be restarted, previous tests may still be running but will be ignored by the AutoTester...

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 5</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_BRANCH</td>
    <td>autotester</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/mmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>b256659937be36f112b9eb695169e0c6f26daa14</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>fec3bc5ebf862e3afb1ee4afa7d0fe40a6d3f7d9</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (mmundt/pyomo)</dt>
  <ul>
    <li>Branch: autotester</li>
    <li>SHA: b256659937be36f112b9eb695169e0c6f26daa14</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: mmundt
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 5</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_BRANCH</td>
    <td>autotester</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/mmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>b256659937be36f112b9eb695169e0c6f26daa14</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>fec3bc5ebf862e3afb1ee4afa7d0fe40a6d3f7d9</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Pull Request MUST BE MERGED MANUALLY BY Project Team - Master Automerge is disabled (in .cfg file)

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

**Review by rmmilewi — APPROVED** [review]
I'm not actually allowed to approve any changes, but that won't stop me from trying! Muhahahahaha!

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           ERROR: PR APPROVAL SET BY UNAPPROVED USER 'rmmilewi', APPROVAL IS INVALID! - This PR must be approved by whitelisted user.

**Review by mrmundt — APPROVED** [review]

**Comment by rmmilewi** [comment]
You can't keep me out forever! I only have to be lucky once, and you have to be lucky every time!

_Disappears in puff of smoke_

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ mrmundt ]!

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 6</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_BRANCH</td>
    <td>autotester</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/mmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>1df63066caa2ba0bd7ae236fcfdd2504f0aa3d8d</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>fec3bc5ebf862e3afb1ee4afa7d0fe40a6d3f7d9</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (mmundt/pyomo)</dt>
  <ul>
    <li>Branch: autotester</li>
    <li>SHA: 1df63066caa2ba0bd7ae236fcfdd2504f0aa3d8d</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: mmundt
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 6</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_BRANCH</td>
    <td>autotester</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/mmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>1df63066caa2ba0bd7ae236fcfdd2504f0aa3d8d</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>fec3bc5ebf862e3afb1ee4afa7d0fe40a6d3f7d9</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Pull Request MUST BE MERGED MANUALLY BY Project Team - Master Automerge is disabled (in .cfg file)

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED by label AT: PRE-TEST INSPECTED! Autotester is Removing Label; this inspection will remain valid until a new commit to source branch is performed.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Failure: Job Pyomo_autotest_Pyomo_trunk_mmundt on Jenkins server at https://jenkins-srn.sandia.gov Does Not Exist
- Other jobs have been previously started - We must stop them...

**Comment by rmmilewi** [comment]
@mmundt Ohh, so that's why my phone is buzzing with notifications! I previously commented on this PR.

**Comment by mrmundt** [comment]
@rmmilewi - Trolololol, sorry, I was doing a major refactor of some AT code. MUH BAD.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Failure: Job Pyomo_autotest_Pyomo_trunk_mmundt on Jenkins server at https://jenkins-srn.sandia.gov Does Not Exist
- Other jobs have been previously started - We must stop them...

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED by label AT: PRE-TEST INSPECTED! Autotester is Removing Label; this inspection will remain valid until a new commit to source branch is performed.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

**Review by e10harvey — APPROVED** [review]

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           ERROR: PR APPROVAL SET BY UNAPPROVED USER 'e10harvey', APPROVAL IS INVALID! - This PR must be approved by approvedusered user.

**Review by mrmundt — APPROVED** [review]

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ mrmundt ]!

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Failure: Job Pyomo_autotest_Pyomo_trunk_mmundt on Jenkins server at https://jenkins-srn.sandia.gov Does Not Exist
- Other jobs have been previously started - We must stop them...

**Pull request closed without merging**
