### PR TITLE
YOLO

### PR DESCRIPTION
**Pull request by mmundt**
## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

**Review by e10harvey — APPROVED** [review]

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           ERROR: PR APPROVAL SET BY UNAPPROVED USER 'e10harvey', APPROVAL IS INVALID! - This PR must be approved by approved user.

**Review by e10harvey — APPROVED** [review]
:+1:

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           ERROR: PR APPROVAL SET BY UNAPPROVED USER 'e10harvey', APPROVAL IS INVALID! - This PR must be approved by approved user.

**Review by mrmundt — APPROVED** [review]

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ mrmundt ]!

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

**Review by mrmundt — APPROVED** [review]

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ mrmundt ]!

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 10</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>11</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/mmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>eed3b8db2ec6192da06237f0faf0595fb6f01320</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>fb0ceec8f662d9e19eef07b30d19be3b25a406e7</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (mmundt/pyomo)</dt>
  <ul>
    <li>Branch: auto-testing</li>
    <li>SHA: eed3b8db2ec6192da06237f0faf0595fb6f01320</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: mmundt
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Error: Jenkins Jobs - A user has pushed a change to the PR before testing completed (New Event: 'committed', ID None). The Jenkins Jobs will be shutdown; Testing of this PR must occur again.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 15 Mins. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 10</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>11</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/mmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>eed3b8db2ec6192da06237f0faf0595fb6f01320</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>fb0ceec8f662d9e19eef07b30d19be3b25a406e7</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

**Review by mrmundt — CHANGES_REQUESTED** [review]
Yeah, no.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           ERROR: PR APPROVAL SET BY UNAPPROVED USER 'mrmundt', APPROVAL IS INVALID! - This PR must be approved by approved user.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

**Review by mrmundt — CHANGES_REQUESTED** [review]
Still no.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           ERROR: PR APPROVAL SET BY UNAPPROVED USER 'mrmundt', APPROVAL IS INVALID! - This PR must be approved by approved user.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

**Review by mrmundt — APPROVED** [review]
I changed my mind. This is fine.
image

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ mrmundt ]!

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 11</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>11</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/mmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>d6119ae98259ef11d01e8339e1ef7b70499a067f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>fb0ceec8f662d9e19eef07b30d19be3b25a406e7</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (mmundt/pyomo)</dt>
  <ul>
    <li>Branch: auto-testing</li>
    <li>SHA: d6119ae98259ef11d01e8339e1ef7b70499a067f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: mmundt
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 11</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>11</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/mmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>d6119ae98259ef11d01e8339e1ef7b70499a067f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>fb0ceec8f662d9e19eef07b30d19be3b25a406e7</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

**Pull request closed without merging**
