### PR TITLE
At mr59 test

### PR DESCRIPTION
**Pull request by e10harvey**
## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

**Review by mmundt — APPROVED** [review]

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           ERROR: PR APPROVAL SET BY UNAPPROVED USER 'mmundt', APPROVAL IS INVALID! - This PR must be approved by approved user.

**Review by mrmundt — APPROVED** [review]

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ mrmundt ]!

**Review by mrmundt — APPROVED** [review]

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ mrmundt ]!

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Failure: Job Pyomo_archive_benchmark_mmundt on Jenkins server at https://jenkins-srn.sandia.gov Does Not Exist
- Other jobs have been previously started - We must stop them...

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - User Requested Retest - Label AT: RETEST will be reset after testing.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 1</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_BRANCH</td>
    <td>at_mr59_test</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>4ee24e4fff0768ccf924139c1197f17319da864f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>8a9e897c97f3fdcbf0fddd47990c54a3436f4717</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (e10harvey/pyomo)</dt>
  <ul>
    <li>Branch: at_mr59_test</li>
    <li>SHA: 4ee24e4fff0768ccf924139c1197f17319da864f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: e10harvey
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - User Requested Retest - Label AT: RETEST will be reset after testing.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 2</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_BRANCH</td>
    <td>at_mr59_test</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>4ee24e4fff0768ccf924139c1197f17319da864f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>8a9e897c97f3fdcbf0fddd47990c54a3436f4717</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (e10harvey/pyomo)</dt>
  <ul>
    <li>Branch: at_mr59_test</li>
    <li>SHA: 4ee24e4fff0768ccf924139c1197f17319da864f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: e10harvey
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Error: Jenkins Jobs - A user has commited a change to the PR before testing completed.  The original testing SHA = 4ee24e4fff0768ccf924139c1197f17319da864f Does not match the current commit SHA = 4ee24e4fff0768ccf924139c1197f17319da864f.  The Jenkins Jobs will be shutdown; Testing of this PR must occur again.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 15 Mins. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 2</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_BRANCH</td>
    <td>at_mr59_test</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>4ee24e4fff0768ccf924139c1197f17319da864f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>8a9e897c97f3fdcbf0fddd47990c54a3436f4717</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - User Requested Retest - Label AT: RETEST will be reset after testing.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 3</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_BRANCH</td>
    <td>at_mr59_test</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>4ee24e4fff0768ccf924139c1197f17319da864f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>8a9e897c97f3fdcbf0fddd47990c54a3436f4717</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (e10harvey/pyomo)</dt>
  <ul>
    <li>Branch: at_mr59_test</li>
    <li>SHA: 4ee24e4fff0768ccf924139c1197f17319da864f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: e10harvey
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - User Requested Retest - Label AT: RETEST will be reset after testing.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 4</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_BRANCH</td>
    <td>at_mr59_test</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>4ee24e4fff0768ccf924139c1197f17319da864f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>8a9e897c97f3fdcbf0fddd47990c54a3436f4717</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (e10harvey/pyomo)</dt>
  <ul>
    <li>Branch: at_mr59_test</li>
    <li>SHA: 4ee24e4fff0768ccf924139c1197f17319da864f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: e10harvey
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - User Requested Retest - Label AT: RETEST will be reset after testing.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 7</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>4ee24e4fff0768ccf924139c1197f17319da864f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>8a9e897c97f3fdcbf0fddd47990c54a3436f4717</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (e10harvey/pyomo)</dt>
  <ul>
    <li>Branch: at_mr59_test</li>
    <li>SHA: 4ee24e4fff0768ccf924139c1197f17319da864f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: e10harvey
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 7</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>4ee24e4fff0768ccf924139c1197f17319da864f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>8a9e897c97f3fdcbf0fddd47990c54a3436f4717</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - User Requested Retest - Label AT: RETEST will be reset after testing.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 8</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>4ee24e4fff0768ccf924139c1197f17319da864f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>8a9e897c97f3fdcbf0fddd47990c54a3436f4717</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (e10harvey/pyomo)</dt>
  <ul>
    <li>Branch: at_mr59_test</li>
    <li>SHA: 4ee24e4fff0768ccf924139c1197f17319da864f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: e10harvey
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - User Requested Retest - Label AT: RETEST will be reset after testing.

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 9</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>4ee24e4fff0768ccf924139c1197f17319da864f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>8a9e897c97f3fdcbf0fddd47990c54a3436f4717</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: PYOMO (e10harvey/pyomo)</dt>
  <ul>
    <li>Branch: at_mr59_test</li>
    <li>SHA: 4ee24e4fff0768ccf924139c1197f17319da864f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: PYUTILS (PyUtilib/pyutilib)</dt>
  <ul>
    <li>Branch: master</li>
    <li>SHA: d99406f2af1fb62268c34453a2fbe6bd4a7348f0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: e10harvey
</details>

**Comment by mrmundt** [comment]
Status Flag 'Jenkins CI / test (pull request)' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Pyomo_autotest_Pyomo_trunk_mmundt</h3>
<ul>
  <li>Build Num: 9</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_SOURCE_SHA</td>
    <td>4ee24e4fff0768ccf924139c1197f17319da864f</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_BRANCH</td>
    <td>main</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_REPO</td>
    <td>https://github.com/mrmundt/pyomo</td>
  </tr>

  <tr>
    <td>PYOMO_TARGET_SHA</td>
    <td>8a9e897c97f3fdcbf0fddd47990c54a3436f4717</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_REPO</td>
    <td>https://github.com/PyUtilib/pyutilib</td>
  </tr>

  <tr>
    <td>PYUTILS_SOURCE_SHA</td>
    <td>d99406f2af1fb62268c34453a2fbe6bd4a7348f0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>PYOMO</td>
  </tr>
</table>
</details>

**Pull request closed without merging**
